CREATE DATABASE IF NOT EXISTS REGISTRO_LOGIN_USUARIOS_MGR;

USE REGISTRO_LOGIN_USUARIOS_MGR;

CREATE TABLE IF NOT EXISTS usuarios (
    username VARCHAR(50) PRIMARY KEY,
    pass VARCHAR(255) NOT NULL
);

TRUNCATE TABLE usuarios;

SELECT * FROM usuarios;